clear;
clc;
load("cook.mat"); 
k = 2; 
E = 1; nu = 1/3; ps=1;   
mat.E = E; mat.nu = nu; mat.ps=ps;
[elem_new,node_new,edgeMap]=getk2_elemnode(elem,node);
sumNode = size(node_new,1);
p = 0.0625;
nodeL = find(node_new(:,1)<0.001);
sL = size(nodeL,1);
nodeR  = find(node(:,1)>48-0.001);   
pface = findFace(node,elem,nodeR);
press = [pface,ones(size(pface,1),1)*p];
fixNode = [nodeL,ones(sL,1),zeros(sL,1);nodeL,2*ones(sL,1),zeros(sL,1)];
fixMes = [fixNode(:,1)+(fixNode(:,2)-1)*sumNode,fixNode(:,3)];
nodeForce = getForce(edgeMap,node_new,elem,press,'y');
GK = globalK(node,elem,node_new,elem_new,mat);
[GK,F] = boundaryCondition(GK,nodeForce,fixMes(:,1),fixMes(:,2),1);
uh = GK\F;
uh = full(uh);
ux = uh(1:sumNode);
uy = uh(sumNode+1:end);
[stress,mises,smax,smin] = calculateStress(node,elem,node_new,elem_new,uh,mat);
Relem_new= nodeReorder(elem_new);
figure;
showsolution(node_new+[ux,uy],Relem_new,uy);